  - name: Lint with pylint
      run: |
        pylint --exit-zero my_source.py
    - name: Test with pytest
      run: |
        pytest
    - name: Code coverage
      run: |
        pytest --cov-report term-missing --cov
    - name: Pydocstyle
      run: |
        pydocstyle